import Head from "next/head";
import About from "../components/About";
import Hero from "../components/Hero";
import MainLayout from "../components/MainLayout";
import Projects from "../components/Projects";
import Services from "../components/Services";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Hero />
        <About />
        <Projects />
        <Services />
      </MainLayout>
    </>
  );
}
